### ISSUE TITLE
AssertionError when calling the action "Gist Templates"

### ISSUE THREAD

**Issue by BorzdeG** [geowarin/gist-templates-plugin#12]
IDEA: IU-140.2285.5

null
java.lang.AssertionError
    at com.gisttemplates.github.Github13.getPassword(Github13.java:28)
    at com.gisttemplates.gist.GistServiceImpl.getGithubClient(GistServiceImpl.java:80)
    at com.gisttemplates.gist.GistServiceImpl.fetchGistList(GistServiceImpl.java:55)
    at com.gisttemplates.action.EditorActionFactory13$GistTemplateActionHandler.createGistTemplatesList(EditorActionFactory13.java:49)
    at com.gisttemplates.action.EditorActionFactory13$GistTemplateActionHandler.doExecute(EditorActionFactory13.java:44)
    at com.intellij.openapi.editor.actionSystem.EditorActionHandler$4.perform(EditorActionHandler.java:217)
    at com.intellij.openapi.editor.actionSystem.EditorActionHandler.doIfEnabled(EditorActionHandler.java:109)
    at com.intellij.openapi.editor.actionSystem.EditorActionHandler.execute(EditorActionHandler.java:214)
    at com.intellij.openapi.editor.actionSystem.EditorAction$1.run(EditorAction.java:98)
    at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:124)
    at com.intellij.openapi.editor.actionSystem.EditorAction.actionPerformed(EditorAction.java:109)
    at com.intellij.openapi.editor.actionSystem.EditorAction.actionPerformed(EditorAction.java:83)
    at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:182)
    at com.intellij.ide.actions.GotoActionAction$5.run(GotoActionAction.java:218)
    at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:332)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:749)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:702)
    at java.awt.EventQueue$3.run(EventQueue.java:696)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:719)
    at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:741)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:576)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:383)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by BorzdeG** [comment]
"Use my github account" = True
GitHub Auth Type = Token

**Comment by BorzdeG** [comment]
link: #5
