### ISSUE TITLE
Cant't get Gists on Intellij 14

### ISSUE THREAD

**Issue by shotaK** [geowarin/gist-templates-plugin#13]
If I try to generate Gist Templates, I am getting this kind of error message: IDE internal error occurred. The error code is presented below:

com.intellij.codeInsight.lookup.impl.LookupImpl.addItem(Lcom/intellij/codeInsight/lookup/LookupElement;Lcom/intellij/codeInsight/completion/PrefixMatcher;)V
java.lang.NoSuchMethodError: com.intellij.codeInsight.lookup.impl.LookupImpl.addItem(Lcom/intellij/codeInsight/lookup/LookupElement;Lcom/intellij/codeInsight/completion/PrefixMatcher;)V
    at com.gisttemplates.action.EditorActionFactory13.showTemplatesLookup(EditorActionFactory13.java:59)
    at com.gisttemplates.action.EditorActionFactory13$GistTemplateActionHandler.doExecute(EditorActionFactory13.java:44)
    at com.intellij.openapi.editor.actionSystem.EditorActionHandler$4.perform(EditorActionHandler.java:217)
    at com.intellij.openapi.editor.actionSystem.EditorActionHandler.doIfEnabled(EditorActionHandler.java:109)
    at com.intellij.openapi.editor.actionSystem.EditorActionHandler.execute(EditorActionHandler.java:214)
    at com.intellij.openapi.editor.actionSystem.EditorAction$1.run(EditorAction.java:98)
    at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:124)
    at com.intellij.openapi.editor.actionSystem.EditorAction.actionPerformed(EditorAction.java:109)
    at com.intellij.openapi.editor.actionSystem.EditorAction.actionPerformed(EditorAction.java:83)
    at com.intellij.ui.popup.PopupFactoryImpl$ActionPopupStep$1.run(PopupFactoryImpl.java:746)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:749)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:702)
    at java.awt.EventQueue$3.run(EventQueue.java:696)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:719)
    at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:734)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:569)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by lxxself** [comment]
Me too

**Comment by suzel** [comment]
com.intellij.codeInsight.lookup.impl.LookupImpl.addItem(Lcom/intellij/codeInsight/lookup/LookupElement;Lcom/intellij/codeInsight/completion/PrefixMatcher;)V
java.lang.NoSuchMethodError: com.intellij.codeInsight.lookup.impl.LookupImpl.addItem(Lcom/intellij/codeInsight/lookup/LookupElement;Lcom/intellij/codeInsight/completion/PrefixMatcher;)V
    at com.gisttemplates.action.EditorActionFactory13.showTemplatesLookup(EditorActionFactory13.java:59)
    at com.gisttemplates.action.EditorActionFactory13$GistTemplateActionHandler.doExecute(EditorActionFactory13.java:44)
    at com.intellij.openapi.editor.actionSystem.EditorActionHandler$4.perform(EditorActionHandler.java:217)
    at com.intellij.openapi.editor.actionSystem.EditorActionHandler.doIfEnabled(EditorActionHandler.java:109)
    at com.intellij.openapi.editor.actionSystem.EditorActionHandler.execute(EditorActionHandler.java:214)
    at com.intellij.openapi.editor.actionSystem.EditorAction$1.run(EditorAction.java:98)
    at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:124)
    at com.intellij.openapi.editor.actionSystem.EditorAction.actionPerformed(EditorAction.java:109)
    at com.intellij.openapi.editor.actionSystem.EditorAction.actionPerformed(EditorAction.java:83)
    at com.intellij.ui.popup.PopupFactoryImpl$ActionPopupStep$1.run(PopupFactoryImpl.java:746)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:209)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:715)
    at java.awt.EventQueue.access$400(EventQueue.java:82)
    at java.awt.EventQueue$2.run(EventQueue.java:676)
    at java.awt.EventQueue$2.run(EventQueue.java:674)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:86)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:685)
    at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:734)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:569)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:296)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:211)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:196)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:188)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)

**Comment by asjustas** [comment]
me too ping @geowarin

**Comment by geowarin** [comment]
Hi Guys. Sorry for keeping you waiting.
The way the plugin provides code snippets in the editor window is kind of a hack. It does not use the public API so every major release of Intellij actually breaks the plugin.

I'm no longer actively maintaining it as you may have noticed.
But I would really like to create a new version of this plugin with a narrower scope.
Namely, maintaining only the latest version of IntelliJ instead of having spaghetti code and try to maintain backward compatibility.

I don't have the time to do this right now but that's definitely in the backlog :smile:

**Comment by christianmagill** [comment]
Much looking forward to this!
