### ISSUE TITLE
NoSuchMethodError / Webstorm 10.0.4

### ISSUE THREAD

**Issue by trendvisor** [geowarin/gist-templates-plugin#15]
get error message when try to generate in webstorm 10.0.4:

com.intellij.codeInsight.lookup.impl.LookupImpl.addItem(Lcom/intellij/codeInsight/lookup/LookupElement;Lcom/intellij/codeInsight/completion/PrefixMatcher;)V

**Comment by trendvisor** [comment]
here are the details:

com.intellij.codeInsight.lookup.impl.LookupImpl.addItem(Lcom/intellij/codeInsight/lookup/LookupElement;Lcom/intellij/codeInsight/completion/PrefixMatcher;)V
java.lang.NoSuchMethodError: com.intellij.codeInsight.lookup.impl.LookupImpl.addItem(Lcom/intellij/codeInsight/lookup/LookupElement;Lcom/intellij/codeInsight/completion/PrefixMatcher;)V
    at com.gisttemplates.action.EditorActionFactory13.showTemplatesLookup(EditorActionFactory13.java:59)
    at com.gisttemplates.action.EditorActionFactory13$GistTemplateActionHandler.doExecute(EditorActionFactory13.java:44)
    at com.intellij.openapi.editor.actionSystem.EditorActionHandler$4.perform(EditorActionHandler.java:217)
    at com.intellij.openapi.editor.actionSystem.EditorActionHandler.doIfEnabled(EditorActionHandler.java:109)
    at com.intellij.openapi.editor.actionSystem.EditorActionHandler.execute(EditorActionHandler.java:214)
    at com.intellij.openapi.editor.actionSystem.EditorAction$1.run(EditorAction.java:98)
    at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:124)
    at com.intellij.openapi.editor.actionSystem.EditorAction.actionPerformed(EditorAction.java:109)
    at com.intellij.openapi.editor.actionSystem.EditorAction.actionPerformed(EditorAction.java:83)
    at com.intellij.ui.popup.PopupFactoryImpl$ActionPopupStep$1.run(PopupFactoryImpl.java:746)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:749)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:702)
    at java.awt.EventQueue$3.run(EventQueue.java:696)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:719)
    at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:734)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:569)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by AlexKR** [comment]
Same for PHPStorm 9.5
