### ISSUE TITLE
Error in Webstorm11

### ISSUE THREAD

**Issue by stefanwalther** [geowarin/gist-templates-plugin#17]
Hi,

in Webstorm 11 I get the following error:

null
java.lang.AssertionError
    at com.gisttemplates.github.Github13.getPassword(Github13.java:28)
    at com.gisttemplates.gist.GistServiceImpl.getGithubClient(GistServiceImpl.java:80)
    at com.gisttemplates.gist.GistServiceImpl.fetchGistList(GistServiceImpl.java:55)
    at com.gisttemplates.gistfiles.NewFileFromGistAction.actionPerformed(NewFileFromGistAction.java:27)
    at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:182)
    at com.intellij.ide.actions.GotoActionAction$7.run(GotoActionAction.java:275)
    at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:337)
    at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:321)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.awt.EventQueue$3.run(EventQueue.java:703)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
    at com.intellij.ide.IdeEventQueue.f(IdeEventQueue.java:861)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:649)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:380)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by stefanwalther** [comment]
I should probably mention that I am using two-factor authentication on GitHub.

**Comment by morganestes** [comment]
I'm guessing this is related to #5 and GitHub tokens.

**Comment by stefanwalther** [comment]
Yes, I can confirm that I only use tokens, not a password.
