### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by sebastianpisula** [geowarin/gist-templates-plugin#20]
> null
> java.lang.AssertionError
> 	at com.gisttemplates.github.Github13.getPassword(Github13.java:28)
> 	at com.gisttemplates.gist.GistServiceImpl.getGithubClient(GistServiceImpl.java:80)
> 	at com.gisttemplates.gist.GistServiceImpl.fetchGistList(GistServiceImpl.java:55)
> 	at com.gisttemplates.action.EditorActionFactory13$GistTemplateActionHandler.createGistTemplatesList(EditorActionFactory13.java:49)
> 	at com.gisttemplates.action.EditorActionFactory13$GistTemplateActionHandler.doExecute(EditorActionFactory13.java:44)
> 	at com.intellij.openapi.editor.actionSystem.EditorActionHandler$4.perform(EditorActionHandler.java:217)
> 	at com.intellij.openapi.editor.actionSystem.EditorActionHandler.doIfEnabled(EditorActionHandler.java:109)
> 	at com.intellij.openapi.editor.actionSystem.EditorActionHandler.execute(EditorActionHandler.java:214)
> 	at com.intellij.openapi.editor.actionSystem.EditorAction.lambda$actionPerformed$0(EditorAction.java:95)
> 	at com.intellij.openapi.editor.actionSystem.EditorAction$$Lambda$895/1765715598.run(Unknown Source)
> 	at com.intellij.openapi.command.impl.CoreCommandProcessor.a(CoreCommandProcessor.java:149)
> 	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:109)
> 	at com.intellij.openapi.editor.actionSystem.EditorAction.actionPerformed(EditorAction.java:104)
> 	at com.intellij.openapi.editor.actionSystem.EditorAction.actionPerformed(EditorAction.java:83)
> 	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:199)
> 	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:215)
> 	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$1.performAction(IdeKeyEventDispatcher.java:587)
> 	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.a(IdeKeyEventDispatcher.java:634)
> 	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$$Lambda$894/525380052.run(Unknown Source)
> 	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:204)
> 	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:633)
> 	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.b(IdeKeyEventDispatcher.java:477)
> 	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:211)
> 	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:657)
> 	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:391)
> 	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
> 	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
> 	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
> 	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
> 	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
> 	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by geowarin** [comment]
The plugin hasn't been updated for a while. It no longer works with latest intellij versions I'm afraid

**Comment by sebastianpisula** [comment]
thank you for info.
