### ISSUE TITLE
Crash if try insert template

### ISSUE THREAD

**Issue by bimawa** [geowarin/gist-templates-plugin#4]
I try insert template from gist on code and plugin is crashed. I use AppCode 2.5.5

**Comment by geowarin** [comment]
Thanks for the feedback.
Could you provide a little more context (stacktrace or crash error) ? 
It seems to work with my AppCode.

**Comment by bimawa** [comment]
Yea. But i have stacktrace only:

```
null
java.lang.AbstractMethodError
    at com.intellij.openapi.editor.actionSystem.EditorAction$1.run(EditorAction.java:82)
    at com.intellij.openapi.command.impl.CommandProcessorImpl.executeCommand(CommandProcessorImpl.java:124)
    at com.intellij.openapi.editor.actionSystem.EditorAction.actionPerformed(EditorAction.java:93)
    at com.intellij.openapi.editor.actionSystem.EditorAction.actionPerformed(EditorAction.java:67)
    at com.intellij.ui.popup.PopupFactoryImpl$ActionPopupStep$1.run(PopupFactoryImpl.java:733)
    at com.intellij.ui.popup.AbstractPopup$18.run(AbstractPopup.java:1256)
    at com.intellij.openapi.wm.impl.FocusManagerImpl.flushRequest(FocusManagerImpl.java:616)
    at com.intellij.openapi.wm.impl.FocusManagerImpl.flushNow(FocusManagerImpl.java:597)
    at com.intellij.openapi.wm.impl.FocusManagerImpl.flushIdleRequests(FocusManagerImpl.java:567)
    at com.intellij.openapi.wm.impl.FocusManagerImpl.access$200(FocusManagerImpl.java:55)
    at com.intellij.openapi.wm.impl.FocusManagerImpl$IdleRunnable.runEdt(FocusManagerImpl.java:102)
    at com.intellij.openapi.util.EdtRunnable$1.run(EdtRunnable.java:28)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:209)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:715)
    at java.awt.EventQueue.access$400(EventQueue.java:82)
    at java.awt.EventQueue$2.run(EventQueue.java:676)
    at java.awt.EventQueue$2.run(EventQueue.java:674)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:86)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:685)
    at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:696)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:524)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:335)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:296)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:211)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:196)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:188)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)
```

**Comment by geowarin** [comment]
Ok I know what is going on... I updated the plugin to be compatible with the API changes in IntelliJ 13.1 (v135)

However, AppCode is still built with API v131. It should be fixed in a few minutes.

**Comment by bimawa** [comment]
Wow Very big thx :dancer:

**Comment by geowarin** [comment]
Well, thank you ;)
The plugin has been updated to 0.3.6 could you please try it and confirm it fixes the issue ?

**Comment by bimawa** [comment]
Yea now it's working. thx a lot for this awesome plugin :+1:
